# Form implementation generated from reading ui file 'gp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(521, 343)
        Dialog.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 188, 501, 141))
        self.groupBox.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.groupBox.setObjectName("groupBox")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 80, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(120, 80, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(200, 80, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(280, 80, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 20, 301, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(380, 10, 71, 41))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(360, 70, 121, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(410, 150, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 148, 391, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(190, 370, 201, 51))
        self.label_4.setObjectName("label_4")
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setGeometry(QtCore.QRect(40, 20, 435, 64))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.checkBox_3.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_2.setText(_translate("Dialog", "CheckBox"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.comboBox.setItemText(0, _translate("Dialog", "светлая"))
        self.comboBox.setItemText(1, _translate("Dialog", "тёмная"))
        self.comboBox.setItemText(2, _translate("Dialog", "очень светлая"))
        self.pushButton.setText(_translate("Dialog", "сгенерировать"))
        self.label_4.setText(_translate("Dialog", "зачем вам нужен этот пароль?"))
        self.label_2.setText(_translate("Dialog", "Generate"))
        self.label_5.setText(_translate("Dialog", "Password"))
